# Generated by Django 5.0.3 on 2024-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='static/images/company')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company',
                'db_table': 'Company',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='static/images/employees')),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Employees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'Report',
                'ordering': ['date'],
            },
        ),
    ]
